definitions:
  customError.AppError:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  domain.User:
    properties:
      birthday:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
    required:
    - birthday
    - email
    - name
    - password
    type: object
  response.UpdateResponse:
    properties:
      birthday:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  response.UserResponse:
    properties:
      birthday:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  response.UsersResponse:
    properties:
      limit:
        type: integer
      offset:
        type: integer
      total:
        type: integer
      users:
        items:
          $ref: '#/definitions/response.UserResponse'
        type: array
    type: object
info:
  contact: {}
paths:
  /users:
    delete:
      consumes:
      - application/json
      description: Delete a user by their ID
      parameters:
      - description: User ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/customError.AppError'
      tags:
      - users
    get:
      consumes:
      - application/json
      description: Get a user by their ID
      parameters:
      - description: User ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/customError.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/customError.AppError'
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/domain.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/customError.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/customError.AppError'
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update an existing user
      parameters:
      - description: User ID
        in: query
        name: id
        required: true
        type: integer
      - description: User updates
        in: body
        name: updates
        required: true
        schema:
          $ref: '#/definitions/response.UpdateResponse'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/customError.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/customError.AppError'
      tags:
      - users
swagger: "2.0"
